<a href="https://colab.research.google.com/github/feiyoung/ReadPapers/blob/master/PyG_learn_v1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Introduction by Example
Data Handling of Graphs

In [2]:
!pip install torch_geometric

     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 1.0/1.0 MB 11.3 MB/s eta 0:00:00


In [8]:
import torch
from torch_geometric.data import Data

edge_index = torch.tensor([[0, 1, 1, 2],
                           [1, 0, 2, 1]], dtype=torch.long)
x = torch.tensor([[-1], [0], [1]], dtype=torch.float)

data = Data(x=x, edge_index=edge_index)

In [4]:
print(data)

Data(x=[3, 1], edge_index=[2, 4])


In [9]:
print(data.edge_index)

tensor([[0, 1, 1, 2],
        [1, 0, 2, 1]])


In [10]:
import torch
from torch_geometric.data import Data

edge_index = torch.tensor([[0, 1],
                           [1, 0],
                           [1, 2],
                           [2, 1]], dtype=torch.long)
x = torch.tensor([[-1], [0], [1]], dtype=torch.float)

data = Data(x=x, edge_index=edge_index.t().contiguous())
#>>> Data(edge_index=[2, 4], x=[3, 1])

In [6]:
print(data)

Data(x=[3, 1], edge_index=[2, 4])


In [7]:
data.edge_index

tensor([[0, 1, 1, 2],
        [1, 0, 2, 1]])

In [11]:
print(data.keys())

['x', 'edge_index']


In [12]:
print(data['x'])

tensor([[-1.],
        [ 0.],
        [ 1.]])


In [13]:
data.x

tensor([[-1.],
        [ 0.],
        [ 1.]])

In [14]:
type(data)

torch_geometric.data.data.Data

In [15]:
str(data)

'Data(x=[3, 1], edge_index=[2, 4])'

In [17]:
for key, item in data: # 双变量循环
    print(f'{key} found in data')
    print(f'{item}')

x found in data
tensor([[-1.],
        [ 0.],
        [ 1.]])
edge_index found in data
tensor([[0, 1, 1, 2],
        [1, 0, 2, 1]])


In [18]:
'edge_attr' in data

False

In [19]:
data.num_nodes

3

In [20]:
data.num_edges

4

In [21]:
data.num_node_features

1

In [22]:
data.has_isolated_nodes()

False

In [23]:
data.has_self_loops()

False

In [24]:
data.is_directed()

False

In [26]:
device = torch.device('cuda')
data = data.to(device)
print(device)

cuda


Common Benchmark Datasets

In [27]:
## This a graph-classication task data
from torch_geometric.datasets import TUDataset

dataset = TUDataset(root='/tmp/ENZYMES', name='ENZYMES')

Extracting /tmp/ENZYMES/ENZYMES/ENZYMES.zip
Processing...
Done!


In [28]:
str(dataset)

'ENZYMES(600)'

In [29]:
type(dataset)

torch_geometric.datasets.tu_dataset.TUDataset

In [30]:
dataset.num_classes

6

In [31]:
type(dataset[0])

torch_geometric.data.data.Data

In [32]:
dataset.num_node_features

3

In [33]:
str(dataset[0])
# We can see that the first graph in the dataset contains 37 nodes, each one having 3 features.
# There are 168/2 = 84 undirected edges and the graph is assigned to exactly one class.
# In addition, the data object is holding exactly one graph-level target.

'Data(edge_index=[2, 168], x=[37, 3], y=[1])'

In [34]:
data = dataset[0]
data.is_undirected()

True

In [36]:
train_dataset = dataset[:540]
str(train_dataset)

'ENZYMES(540)'

In [39]:
test_dataset = dataset[540:]
str(test_dataset)

'ENZYMES(60)'

In [41]:
## Permute all graphs
dataset = dataset.shuffle()
print(dataset)

ENZYMES(600)


In [42]:
perm = torch.randperm(len(dataset))
print(perm)
dataset = dataset[perm]
print(dataset)

tensor([106, 579, 327, 260, 119, 325, 529, 172, 413, 368, 475, 444,  79, 467,
        559, 421, 456, 422, 423, 509, 152, 515, 316,   4, 191, 461, 232, 465,
        218,  85, 177, 160, 244, 301, 326,   9, 540, 440,  12,  81, 286, 155,
        378, 102, 269, 330, 376, 418, 103, 575,  82, 582, 549, 497, 168, 110,
         50, 332, 498, 312,  97, 410, 565, 357, 210, 213, 587, 292, 288, 123,
        573, 564,  46, 131, 463, 425, 144, 415, 132, 527, 533, 333, 580, 454,
        151, 397, 343, 209, 313, 489, 287, 520, 212, 462, 537, 249,  90, 250,
        473,  83, 129, 530, 162, 178, 328, 101, 445, 451, 389, 359, 262, 128,
        113, 118, 174, 558,   2, 270, 185, 583, 195, 496,  89, 369, 570,  64,
        417, 183, 547, 289, 450, 395,  14, 519, 335, 293, 362, 478,  38,  99,
         76, 455, 483,  22, 192,  94,  73, 240, 349, 424,   0,  20, 223, 446,
        517, 159, 227, 563,  88, 516, 271, 367, 348, 510, 584, 390, 382, 392,
        407, 137, 352, 525,  17, 474, 290, 284, 411, 460, 534, 1

In [43]:
from torch_geometric.datasets import Planetoid

dataset = Planetoid(root='/tmp/Cora', name='Cora')

Processing...
Done!


In [45]:
len(dataset)
print(dataset[0])

Data(x=[2708, 1433], edge_index=[2, 10556], y=[2708], train_mask=[2708], val_mask=[2708], test_mask=[2708])


In [46]:
dataset.num_classes

7

In [48]:
data = dataset[0]
data.is_undirected()

True

In [50]:
data.train_mask # mask is a bool value

tensor([ True,  True,  True,  ..., False, False, False])

In [49]:
data.train_mask.sum().item()

140

In [51]:
data.val_mask.sum().item() # The validation set is similar to the data that help select the tuning parameters, to guide the training process.

500

In [52]:
data.test_mask.sum().item()

1000

Mini-batches

In [53]:
from torch_geometric.datasets import TUDataset
from torch_geometric.loader import DataLoader
dataset = TUDataset(root='/tmp/ENZYMES', name='ENZYMES', use_node_attr=True)
loader = DataLoader(dataset, batch_size=32, shuffle=True)
print(loader)

In [55]:
for batch in loader:
    print(batch)

DataBatch(edge_index=[2, 4048], x=[1077, 21], y=[32], batch=[1077], ptr=[33])
DataBatch(edge_index=[2, 4474], x=[1135, 21], y=[32], batch=[1135], ptr=[33])
DataBatch(edge_index=[2, 4534], x=[1191, 21], y=[32], batch=[1191], ptr=[33])
DataBatch(edge_index=[2, 4150], x=[1090, 21], y=[32], batch=[1090], ptr=[33])
DataBatch(edge_index=[2, 4168], x=[1081, 21], y=[32], batch=[1081], ptr=[33])
DataBatch(edge_index=[2, 3794], x=[977, 21], y=[32], batch=[977], ptr=[33])
DataBatch(edge_index=[2, 3340], x=[948, 21], y=[32], batch=[948], ptr=[33])
DataBatch(edge_index=[2, 3952], x=[1029, 21], y=[32], batch=[1029], ptr=[33])
DataBatch(edge_index=[2, 3670], x=[964, 21], y=[32], batch=[964], ptr=[33])
DataBatch(edge_index=[2, 3522], x=[924, 21], y=[32], batch=[924], ptr=[33])
DataBatch(edge_index=[2, 4408], x=[1135, 21], y=[32], batch=[1135], ptr=[33])
DataBatch(edge_index=[2, 4378], x=[1283, 21], y=[32], batch=[1283], ptr=[33])
DataBatch(edge_index=[2, 4002], x=[1062, 21], y=[32], batch=[1062], ptr=

Data Transforms

In [56]:
from torch_geometric.datasets import ShapeNet

dataset = ShapeNet(root='/tmp/ShapeNet', categories=['Airplane'])

dataset[0]

Extracting /tmp/ShapeNet/shapenetcore_partanno_segmentation_benchmark_v0_normal.zip
Processing...
Done!


Data(x=[2518, 3], y=[2518], pos=[2518, 3], category=[1])

In [57]:
import torch_geometric.transforms as T
from torch_geometric.datasets import ShapeNet

dataset = ShapeNet(root='/tmp/ShapeNet', categories=['Airplane'],
                    pre_transform=T.KNNGraph(k=6))

dataset[0]

/usr/local/lib/python3.10/dist-packages/torch_geometric/data/dataset.py:214: UserWarning: The `pre_transform` argument differs from the one used in the pre-processed version of this dataset. If you want to make use of another pre-processing technique, make sure to delete '/tmp/ShapeNet/processed' first
  warnings.warn(


Data(x=[2518, 3], y=[2518], pos=[2518, 3], category=[1])

In [58]:
import torch_geometric.transforms as T
from torch_geometric.datasets import ShapeNet

dataset = ShapeNet(root='/tmp/ShapeNet', categories=['Airplane'],
                    pre_transform=T.KNNGraph(k=6),
                    transform=T.RandomJitter(0.01))

dataset[0]

Data(x=[2518, 3], y=[2518], pos=[2518, 3], category=[1])

Learning Methods on Graphs

In [59]:
from torch_geometric.datasets import Planetoid

dataset = Planetoid(root='/tmp/Cora', name='Cora')

In [62]:
import torch
import torch.nn.functional as F
from torch_geometric.nn import GCNConv

In [63]:
class GCN(torch.nn.Module):
    def __init__(self):
        super().__init__()
        self.conv1 = GCNConv(dataset.num_node_features, 16)
        self.conv2 = GCNConv(16, dataset.num_classes)

    def forward(self, data):
        x, edge_index = data.x, data.edge_index

        x = self.conv1(x, edge_index)
        x = F.relu(x)
        x = F.dropout(x, training=self.training)
        x = self.conv2(x, edge_index)

        return F.log_softmax(x, dim=1)

In [64]:
device = torch.device('cuda' if torch.cuda.is_available() else 'cpu')
model = GCN().to(device)
data = dataset[0].to(device)
optimizer = torch.optim.Adam(model.parameters(), lr=0.01, weight_decay=5e-4)


In [65]:
print(optimizer)

Adam (
Parameter Group 0
    amsgrad: False
    betas: (0.9, 0.999)
    capturable: False
    differentiable: False
    eps: 1e-08
    foreach: None
    fused: None
    lr: 0.01
    maximize: False
    weight_decay: 0.0005
)


In [66]:
print(model)

GCN(
  (conv1): GCNConv(1433, 16)
  (conv2): GCNConv(16, 7)
)


In [75]:
100 % 50

0

In [76]:
model.train()
for epoch in range(200):
    optimizer.zero_grad()
    out = model(data)
    if epoch ==1:
      print(out)
    loss = F.nll_loss(out[data.train_mask], data.y[data.train_mask])
    if epoch % 50 == 0:
      print(f'epoch={epoch},loss value is: {loss},\n')
    loss.backward()
    optimizer.step()

epoch=0,loss value is: 0.014416670426726341,

tensor([[-1.0044e+01, -1.0165e+01, -8.8782e+00,  ..., -7.8491e+00,
         -8.2734e+00, -1.0062e+01],
        [-8.4510e+00, -1.3572e+01, -1.2559e+01,  ..., -4.6266e-04,
         -1.2581e+01, -8.7553e+00],
        [-1.1686e+01, -2.0217e+01, -1.7014e+01,  ..., -4.2676e-05,
         -1.8325e+01, -1.6904e+01],
        ...,
        [-2.0096e+00, -2.2957e-01, -7.9513e+00,  ..., -7.2688e+00,
         -5.6494e+00, -6.3931e+00],
        [-8.4112e+00, -7.9774e+00, -7.6068e+00,  ..., -7.7642e+00,
         -9.7363e+00, -1.2046e+01],
        [-8.3248e+00, -7.8859e+00, -7.6521e+00,  ..., -7.3621e+00,
         -8.0687e+00, -1.2362e+01]], device='cuda:0',
       grad_fn=<LogSoftmaxBackward0>)
epoch=50,loss value is: 0.017802931368350983,

epoch=100,loss value is: 0.017094748094677925,

epoch=150,loss value is: 0.018516769632697105,



In [72]:
model.eval()
print(model(data).shape) # compute the prediction for all nodes
print(model(data))

torch.Size([2708, 7])
tensor([[-8.6938e+00, -8.7502e+00, -9.2916e+00,  ..., -8.2936e+00,
         -9.8322e+00, -9.9873e+00],
        [-1.2680e+01, -1.3262e+01, -1.3678e+01,  ..., -1.3709e-05,
         -1.5348e+01, -1.1957e+01],
        [-1.0908e+01, -1.0998e+01, -1.2009e+01,  ..., -1.5687e-04,
         -1.3238e+01, -1.0556e+01],
        ...,
        [-7.5489e-01, -1.1072e+00, -7.4873e+00,  ..., -7.3959e+00,
         -1.7942e+00, -3.8324e+00],
        [-8.0189e+00, -6.8850e+00, -8.2132e+00,  ..., -6.5319e+00,
         -8.9948e+00, -1.0606e+01],
        [-7.1159e+00, -6.1808e+00, -7.3517e+00,  ..., -6.3592e+00,
         -7.9447e+00, -9.7197e+00]], device='cuda:0',
       grad_fn=<LogSoftmaxBackward0>)


In [73]:
pred = model(data).argmax(dim=1)
correct = (pred[data.test_mask] == data.y[data.test_mask]).sum()
acc = int(correct) / int(data.test_mask.sum())
print(f'Accuracy: {acc:.4f}')

Accuracy: 0.8040


Excerse

In [77]:
#from torch_geometric.datasets import IMDB-BINARY
#dataset = Planetoid(root='/tmp/Cora', name='Cora')
dataset = TUDataset(root='/tmp/IMDB-BINARY', name='IMDB-BINARY')

Extracting /tmp/IMDB-BINARY/IMDB-BINARY/IMDB-BINARY.zip
Processing...
Done!


In [78]:
print(dataset)

IMDB-BINARY(1000)


In [79]:
data = dataset[0]
print(data)

Data(edge_index=[2, 146], y=[1], num_nodes=20)


In [82]:
import torch as th
dataset.train_mask = th.tensor([True] * 1000)

In [85]:
dataset[0]

Data(edge_index=[2, 146], y=[1], num_nodes=20)

In [87]:
import torch
from torch_geometric.datasets import TUDataset
from torch_geometric.data import DataLoader
from torch.utils.data import random_split

# Set seed for reproducibility
seed = 42
torch.manual_seed(seed)

# Load IMDB-BINARY dataset
dataset = TUDataset(root='data/IMDB-BINARY', name='IMDB-BINARY')

# Define sizes for training, validation, and test sets
num_data = len(dataset)
train_ratio, val_ratio, test_ratio = 0.8, 0.1, 0.1
num_train = int(train_ratio * num_data)
num_val = int(val_ratio * num_data)
num_test = num_data - num_train - num_val

# Split dataset into training, validation, and test sets
train_dataset, val_dataset, test_dataset = random_split(
    dataset, [num_train, num_val, num_test], generator=torch.manual_seed(seed)
)

# Create DataLoader for each set
train_loader = DataLoader(train_dataset, batch_size=64, shuffle=True)
val_loader = DataLoader(val_dataset, batch_size=64, shuffle=False)
test_loader = DataLoader(test_dataset, batch_size=64, shuffle=False)

# Example usage of the loaders
for batch in train_loader:
    # Perform training operations
    pass

for batch in val_loader:
    # Perform validation operations
    pass

for batch in test_loader:
    # Perform test operations
    pass


Extracting data/IMDB-BINARY/IMDB-BINARY/IMDB-BINARY.zip
Processing...
Done!
/usr/local/lib/python3.10/dist-packages/torch_geometric/deprecation.py:22: UserWarning: 'data.DataLoader' is deprecated, use 'loader.DataLoader' instead
  warnings.warn(out)


In [89]:
train_dataset[0]

Data(edge_index=[2, 66], y=[1], num_nodes=13)